### PR TITLE
Update PHPUnit version

### PR DESCRIPTION
**Pull request by paul-m**

### CODE REVIEW

**Comment by paul-m** [comment]
This PR does a few things:
- Update the maximum PHPUnit version to 9.4.x. We can't use 9.5.x because it restricts how we use `onlyMethods()` to mock non-existent methods. Follow-up: https://github.com/GetDKAN/mock-chain/issues/15
- Adopts min/max dependency testing. This is where we run the tests using both `composer update` and `composer update --prefer-lowest`, in order to ensure that our dependency constraints are real.
- Restricts us to PHP <9.0. PHP 8.1 introduces a deprecation that shows up in PHPUnit: "Deprecated: PHPUnit\Runner\DefaultTestResultCache implements the Serializable interface, which is deprecated." https://wiki.php.net/rfc/phase_out_serializable Presumably later updates to PHPUnit will address this.

**Comment by dafeder** [comment]
@paul-m thanks for figuring this out. Does this change the _minimum_ compatibility at all?

**Comment by paul-m** [comment]
> @paul-m thanks for figuring this out. Does this change the _minimum_ compatibility at all?

Currently we're locked at a minimum of PHPUnit 5.7.7. When we use that, we get this:
```
$ composer update --prefer-lowest
[ ... ]
$ composer show phpunit/phpunit | grep versions
versions : * 5.7.7
[ ... ]

1) MockChainTest\ChainTest::testDocs
Error: Call to undefined method PHPUnit_Framework_MockObject_MockBuilder::onlyMethods()

/var/www/html/src/Chain.php:183
/var/www/html/src/Chain.php:144
/var/www/html/src/Chain.php:115
/var/www/html/test/ChainTest.php:25
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:51

etc....
```
Some research tells us that `onlyMethods()` [first shows up in PHPUnit 8.3.0](https://github.com/sebastianbergmann/phpunit/blob/8.3.0/ChangeLog-8.3.md).

So basically if you tried to use PHPUnit earlier than 8.3.0, you ended up not being able to use mock-chain.

Consulting packagist.org we find that 8.3.0 has a minimum PHP version of 7.2, so I'll change that in our composer.json. (I think I had set a minimum of 7.3 because I stopped working on it.)

**Comment by paul-m** [comment]
Superseded by https://github.com/GetDKAN/mock-chain/pull/17

**Pull request closed without merging**
